autoclip: true
autoimport: true
cliptimeout: 45
exportkeys: true
nocolor: false
nopager: false
notifications: true
parsing: true
path: /home/murin/.local/share/gopass/stores/root
safecontent: true
mounts: {}
